### ISSUE TITLE
Description of Item not showing in Gear or Ability Tab overview anymore.

### ISSUE THREAD

**Issue by dennyp02** [TomCosaert/FoundryVTT-ICRPG#3]
Ever since the latest update i've done to 0.7.5, i cant see the description in small text under the items names anymore. You now have to double click into the item to see its description.
I thought it was a really nice feature, and would love to have it back!

Thanks for the really good work on this! I love ICRPG to bits and your system module makes it so easy to play!

![image](https://user-images.githubusercontent.com/58830475/97120916-f14ee480-171a-11eb-8b37-bfe388dd72ed.png)
![image](https://user-images.githubusercontent.com/58830475/97120922-0297f100-171b-11eb-9db3-c0af4fb0644a.png)

**Comment by TomCosaert** [comment]
Hey @dennypahlke! Thanks for reporting this issue. 
I looked into it and it seems this is actually a bug in Foundry VTT 0.7.5.
I submitted a [bug report on the Foundry tracker](https://gitlab.com/foundrynet/foundryvtt/-/issues/3984) for it, was confirmed, and it will be fixed in **Foundry VTT 0.7.6**.
